name: Test Status

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '14', '12' ]
    name: Node ${{ matrix.node }} validation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
        env:
          HETZNER_API_KEY: ${{ secrets.HETZNER_API_KEY }}
      - run: npm audit --audit-level=critical
